//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimViecLam.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppDB : DbContext
    {
        public AppDB()
            : base("name=AppDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CtPhieuDangTuyen> CtPhieuDangTuyens { get; set; }
        public virtual DbSet<DanhSachCongViec> DanhSachCongViecs { get; set; }
        public virtual DbSet<HoSoXinViec> HoSoXinViecs { get; set; }
        public virtual DbSet<NguoiTimViec> NguoiTimViecs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhaTuyenDung> NhaTuyenDungs { get; set; }
        public virtual DbSet<PhieuDangTuyen> PhieuDangTuyens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
