//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimViecLam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiTimViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiTimViec()
        {
            this.HoSoXinViecs = new HashSet<HoSoXinViec>();
        }
    
        public int MaNguoiTimViec { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string HinhAnh { get; set; }
        public string TrinhDo { get; set; }
        public string ChuyenNganh { get; set; }
        public string BangCap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoXinViec> HoSoXinViecs { get; set; }
    }
}
