//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimViecLam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDangTuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDangTuyen()
        {
            this.CtPhieuDangTuyens = new HashSet<CtPhieuDangTuyen>();
        }
    
        public int MaPhieuDangTuyen { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> MaNhaTuyenDung { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CtPhieuDangTuyen> CtPhieuDangTuyens { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhaTuyenDung NhaTuyenDung { get; set; }
    }
}
